
version: 2

sources:
  - name: netsuite
    database: source
    schema: netsuite
    tables:
      - name: address
      - name: addresstype
      - name: awbuildversion
      - name: billofmaterials
      - name: businessentity
      - name: businessentityaddress
      - name: businessentitycontact
      - name: company
      - name: contacttype
      - name: contract
      - name: countryregion
      - name: countryregioncurrency
      - name: creditcard
      - name: culture
      - name: currency
      - name: currencyrate
      - name: customer
      - name: databaselog
      - name: department
      - name: document
      - name: emailaddress
      - name: employee
      - name: employeedepartmenthistory
      - name: employeepayhistory
      - name: errorlog
      - name: illustration
      - name: jobcandidate
      - name: location
      - name: password
      - name: person
      - name: personcreditcard
      - name: personphone
      - name: phonenumbertype
      - name: product
      - name: productcategory
      - name: productcosthistory
      - name: productdescription
      - name: productdocument
      - name: productinventory
      - name: productlistpricehistory
      - name: productmodel
      - name: productmodelillustration
      - name: productmodelproductdescriptionculture
      - name: productphoto
      - name: productproductphoto
      - name: productreview
      - name: productsubcategory
      - name: productvendor
      - name: purchaseorderdetail
      - name: purchaseorderheader
      - name: salesorderdetail
      - name: salesorderheader
      - name: salesorderheadersalesreason
      - name: salesperson
      - name: salespersonquotahistory
      - name: salesreason
      - name: salestaxrate
      - name: salesterritory
      - name: salesterritoryhistory
      - name: scrapreason
      - name: shift
      - name: shipmethod
      - name: shoppingcartitem
      - name: specialoffer
      - name: specialofferproduct
      - name: stateprovince
      - name: transactionhistory
      - name: transactionhistoryarchive
      - name: unitmeasure
      - name: vendor
      - name: workorder
      - name: workorderrouting